window.DIGIBOOK_CATALOG = [
  ["Le Personal MBA", "Josh Kaufman", "Finance & Business"],
  ["L'ego est l'ennemi", "Ryan Holiday", "Developpement personnel"],
  ["12 principes du succes", "", "Developpement personnel"],
  ["12 lecons de rhetorique pour prendre le pouvoir", "", "Communication & Influence"],
  ["365 conseils pour investir dans l'immobilier", "", "Finance & Business"],
  ["365 jours d'autodiscipline", "Martin Meadows", "Developpement personnel"],
  ["40 ans de prison ou 5 ans de travail force", "Maxime", "Developpement personnel"],
  ["45 secondes qui changeront votre vie", "", "Developpement personnel"],
  ["500 idees de business pour entreprendre", "", "Finance & Business"],
  ["7 secrets pour changer de vie maintenant", "", "Developpement personnel"],
  ["99 trucs pour s'enrichir", "", "Finance & Business"],
  ["Aliko Dangote : les 21 secrets", "Achille Wealth PhD", "Finance & Business"],
  ["Arrete la procrastination", "Francis Wayne Jr.", "Developpement personnel"],
  ["Atteindre l'excellence", "Robert Greene", "Developpement personnel"],
  ["Avoir le courage de ne pas etre aime", "", "Developpement personnel"],
  ["Ce que vous avez a dire n'interesse personne", "", "Communication & Influence"],
  ["Comment parler a n'importe qui dans toute situation", "", "Communication & Influence"],
  ["Comment parler en public", "Dale Carnegie", "Communication & Influence"],
  ["Comment parler en public - edition 2", "", "Communication & Influence"],
  ["Comment se faire des amis", "Dale Carnegie", "Communication & Influence"],
  ["Attirer le meilleur par la pensee positive", "", "Developpement personnel"],
  ["Comment parler a n'importe qui : 92 techniques", "Leil Lowndes", "Communication & Influence"],
  ["Comment se faire des amis - edition 2", "", "Communication & Influence"],
  ["Dark Psychology Secrets", "", "Psychologie & Strategie"],
  ["De l'idee a la creation d'entreprise", "", "Finance & Business"],
  ["Devenir riche, ca s'apprend", "", "Finance & Business"],
  ["De zero a un", "Peter Thiel", "Finance & Business"],
  ["Decouvrir un sens a sa vie", "Viktor E. Frankl", "Psychologie & Strategie"],
  ["La loi de l'attraction", "Esther et Jerry Hicks", "Developpement personnel"],
  ["Independance financiere : 19 systemes simples", "Lavoie", "Finance & Business"],
  ["Influence et manipulation", "Robert Cialdini", "Communication & Influence"],
  ["Je suis Kunta", "", "Psychologie & Strategie"],
  ["La chevre de ma mere", "Ricardo Kaniama", "Psychologie & Strategie"],
  ["La fabrique de pauvres", "", "Finance & Business"],
  ["La philosophie du succes", "Napoleon Hill", "Developpement personnel"],
  ["La puissance de la pensee creatrice", "", "Developpement personnel"],
  ["La puissance de votre subconscient", "", "Psychologie & Strategie"],
  ["La retraite a 40 ans", "Pilotte", "Finance & Business"],
  ["La semaine de 4 heures", "Timothy Ferriss", "Finance & Business"],
  ["L'art d'avoir toujours raison - edition 1", "Arthur Schopenhauer", "Communication & Influence"],
  ["L'art d'avoir toujours raison - edition 2", "Arthur Schopenhauer", "Communication & Influence"],
  ["L'art de la guerre", "Sun Tzu", "Psychologie & Strategie"],
  ["L'art de la meditation", "", "Developpement personnel"],
  ["L'art subtil de s'en foutre", "Mark Manson", "Developpement personnel"],
  ["L'autodiscipline quotidienne", "", "Developpement personnel"],
  ["Le chemin de la fortune", "Benjamin Franklin", "Finance & Business"],
  ["Le chemin de la fortune - edition 2", "", "Finance & Business"],
  ["Le grand livre du coaching", "", "Developpement personnel"],
  ["Le marketing pour les nuls", "", "Finance & Business"],
  ["Le pouvoir des habitudes", "", "Developpement personnel"],
  ["L'effet cumule", "Darren Hardy", "Developpement personnel"],
  ["Le quadrant du cashflow", "Robert Kiyosaki", "Finance & Business"],
  ["Les entrepreneurs de legende", "", "Finance & Business"],
  ["Les hommes viennent de Mars, les femmes viennent de Venus", "John Gray", "Psychologie & Strategie"],
  ["Les lois de la nature humaine", "Robert Greene", "Psychologie & Strategie"],
  ["Les manipulateurs sont parmi nous", "", "Psychologie & Strategie"],
  ["Les secrets d'un esprit millionnaire", "T. Harv Eker", "Finance & Business"],
  ["Les vertus de l'echec", "Charles Pepin", "Developpement personnel"],
  ["Les 7 habitudes de ceux qui realisent tout ce qu'ils entreprennent", "Stephen R. Covey", "Developpement personnel"],
  ["Les secrets de la longevite d'un couple", "", "Psychologie & Strategie"],
  ["L'essentiel de la macro-economie", "", "Finance & Business"],
  ["L'homme le plus riche de Babylone", "George S. Clason", "Finance & Business"],
  ["L'intelligence emotionnelle", "", "Psychologie & Strategie"],
  ["L'investisseur intelligent", "Benjamin Graham", "Finance & Business"],
  ["L'audace d'entreprendre", "", "Finance & Business"],
  ["L'obstacle est le chemin", "Ryan Holiday", "Developpement personnel"],
  ["La loi du succes", "", "Developpement personnel"],
  ["L'opium du peuple", "Karl Marx", "Psychologie & Strategie"],
  ["Management et marketing du luxe", "", "Finance & Business"],
  ["Management des ressources humaines", "Michel Ferrary", "Finance & Business"],
  ["Management et gestion des ressources humaines", "", "Finance & Business"],
  ["Manipulation : ne vous laissez plus faire", "", "Psychologie & Strategie"],
  ["Marketing spirituel", "Bob Proctor", "Finance & Business"],
  ["Miracle Morning", "Hal Elrod", "Developpement personnel"],
  ["L'autoroute du millionnaire", "MJ DeMarco", "Finance & Business"],
  ["Ne coupez jamais la poire en deux", "Chris Voss et Tahl Raz", "Communication & Influence"],
  ["Ce dont je suis certaine", "Oprah Winfrey", "Developpement personnel"],
  ["Pere riche, pere pauvre", "Robert T. Kiyosaki", "Finance & Business"],
  ["Personnalite Plus", "Florence Littauer", "Psychologie & Strategie"],
  ["Petites habitudes, grandes reussites", "Onur Karapinar", "Developpement personnel"],
  ["Plus malin que le diable", "Napoleon Hill", "Developpement personnel"],
  ["Pouvoirs psychiques et realisation spirituelle", "Michel Coquet", "Psychologie & Strategie"],
  ["Power : les 48 lois du pouvoir", "Robert Greene", "Psychologie & Strategie"],
  ["Psychologie de la seduction", "", "Psychologie & Strategie"],
  ["Pouvez-vous devenir millionnaire et aller au ciel", "R. Kaniama", "Finance & Business"],
  ["Reflechissez et devenez riche", "Napoleon Hill", "Finance & Business"],
  ["Reinventez votre vie", "Arnaud Collery", "Developpement personnel"],
  ["L'ecole des affaires", "Robert Kiyosaki", "Finance & Business"],
  ["L'art de la seduction", "Robert Greene", "Psychologie & Strategie"],
  ["Se liberer des pensees", "Lionel Cruzille", "Psychologie & Strategie"],
  ["Self-Made-Man", "", "Finance & Business"],
  ["Si tu veux changer ta vie, commence par faire ton lit", "", "Developpement personnel"],
  ["Commencer par pourquoi", "Simon Sinek", "Finance & Business"],
  ["Strategie : les 33 lois de la guerre", "Robert Greene", "Psychologie & Strategie"],
  ["Surmonter ses complexes", "Benedicte Nadaud et Karine Zagaroli", "Developpement personnel"],
  ["Systeme 1 / Systeme 2", "Daniel Kahneman", "Psychologie & Strategie"],
  ["The One Thing", "Gary Keller et Jay Papasan", "Developpement personnel"],
  ["Tout le monde merite d'etre riche", "", "Finance & Business"],
  ["Un an pour gagner un million", "Moran", "Finance & Business"],
  ["Un rien peut tout changer", "James Clear", "Developpement personnel"],
].map(([title, author, category]) => ({
  id: crypto.randomUUID(),
  title,
  author,
  category,
  cover: "",
}));
